=== Abdelrahman-kamall/DBMS/dbs/test/t1.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT t1 (row)*>
	<!ELEMENT row (column1,column2,column3)>
	<!ELEMENT column1 (#PCDATA)>
	<!ATTLIST column1 type CDATA #FIXED "int">
	<!ELEMENT column2 (#PCDATA)>
	<!ATTLIST column2 type CDATA #FIXED "varchar">
	<!ELEMENT column3 (#PCDATA)>
	<!ATTLIST column3 type CDATA #FIXED "int">

=== Abdelrahman-kamall/DBMS/dbs/test/t1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE t1 PUBLIC "" "t1.dtd">
<t1>
<row>
<column1 type="int">2</column1>
<column2 type="varchar">value</column2>
<column3 type="int">3</column3>
</row>
<row>
<column1 type="int">2</column1>
<column2 type="varchar">value</column2>
<column3 type="int">3</column3>
</row>
</t1>
